### ISSUE TITLE
Apex Graph X, Y axis filter component

### ISSUE THREAD

**Issue by Sathvika98** [CentralLaserFacility/CLF.DotNet.Blazor.Components#2]
```[tasklist]
### Tasks
- [ ] https://github.com/CentralLaserFacility/CLF.DotNet.Blazor.Components/issues/3
- [ ] Update Spectrometer razor pages to use the component
- [ ] Update Oscilloscope razor pages to use the component
```
